### ISSUE TITLE
where is the ur_control 

### ISSUE THREAD

**Issue by wearefiv** [cambel/ur_ikfast#1]
hello！I  use this package but i can not find the package named ur_control

**Comment by cambel** [comment]
Hi!

I didn't notice the dependency on ur_control! my bad. I updated the repo, the ur_control shouldn't be necessary anymore.
However, if you want you can also check my other [repo](https://github.com/cambel/ur3) where you would find the ur_control package

**Comment by wearefiv** [comment]
hello! it still have a bug. No module named 'ur3_ikfast'.

**Comment by cambel** [comment]
@wearefiv  could you be more specific on what are you trying to do and when is the error occurring?
It seems to me that you are not compiling the module correctly as `ur3_ikfast` is what you would be able to import if the library is compiled

**Comment by wearefiv** [comment]
> @wearefiv could you be more specific on what are you trying to do and when is the error occurring?
> It seems to me that you are not compiling the module correctly as `ur3_ikfast` is what you would be able to import if the library is compiled

I want to run a python file to test the ur_ikfast. When I run that file, it occurs a error .
the error is as follow.
import ur3_ikfast as ur_ikfast
ModuleNotFoundError: No module named 'ur3_ikfast'
the error is from here

      def __init__(self, robot_name):     
           if robot_name == 'ur3':
               import ur3_ikfast as ur_ikfast
I have aleady let the ur3_ikfast.so in python site package

**Comment by cambel** [comment]
> I have aleady let the ur3_ikfast.so in python site package

I don't know what you mean by that, but I recommend you compile this library using the steps described in the README.md file, that way you shouldn't need to move the *.so files manually.

> Easy to install and use:
> Clone
> install dependencies
> sudo apt-get install libblas-dev liblapack-dev
> 
> pip install --user numpy Cython
> 
> install using pip
> $ git clone https://github.com/cambel/ur_ikfast.git
> $ cd ur_ikfast
> $ pip install -e .
