### ISSUE TITLE
can not get same rotation matrixs in ros

### ISSUE THREAD

**Issue by sunnymints** [cambel/ur_ikfast#2]
Thank you for your work.
we want to use your code to creat the solutions for ur5. But we get  different solutions when we calculate the rotation matrixs between from ROS and your code.
for examp,we get the rotation matrixs from quaternion in ros:
[ 9.44e-05    1                9.762e-05   -1.0915e-01
 -1.56e-04   9.76e-05    -9.999e-01   6.04687e-01
 -1               9.440e-05  1.5637e-04   4.318e-01  ]

but your code from jiont angle is :
rotation matrixs:
[ 1                9.746e-05    -9.446e-5     -1.0915e-01
  9.76e-05    -9.999e-01  1.56e-04       6.04687e-01
- 9.440e-05  -1.56e-04    -1                   4.318e-01]

We can see the two rotation matrixs have same  position information，but the rotation part seem to be in other coordinate system

**Comment by cambel** [comment]
@sunnymints Hi,
I see, first I would like to know which link are you considering as your end-effector as UR robots have two `ee_link` and `tool0`. I think I used the `tool0` so that is why we may have a different orientation but the same position.

**Comment by sunnymints** [comment]
> @sunnymints Hi,
> I see, first I would like to know which link are you considering as your end-effector as UR robots have to `ee_link` and `tool0`. I think I used the `tool0` so that is why we may have a different orientation but the same position.

thanks for your answer. you are true!

**Comment by thes0796** [comment]
How can I run this file ?

**Comment by cambel** [comment]
@thes0796 see the examples: 
- https://github.com/cambel/ur_ikfast/blob/master/examples/demo.py
- https://github.com/cambel/ur_ikfast/blob/master/examples/demo2.py
