### ISSUE TITLE
ikfast61.cpp generation error for ur5

### ISSUE THREAD

**Issue by chinmay1148** [cambel/ur_ikfast#3]
The links provided for .cpp file generation (using universal robot ur_description urdf) is generating error.  Can u share the urdf file ?  In your ur5 folder the urdf or dae is not shared.

I skipped the moveit_ikfast round off to 5 decimal place.  

Did you also use ur5.xml format (from https://github.com/andyzeng/ikfastpy) to generate ikfast61.cpp file ?

**Comment by cambel** [comment]
Which error are you getting?

> I skipped the moveit_ikfast round off to 5 decimal places.

Are you trying to generate your own IKfast database? or are you trying to use the ones I am providing here?

> Did you also use ur5.xml format (from https://github.com/andyzeng/ikfastpy) to generate ikfast61.cpp file?

I used the official ur5 URDF file following the moveit_ikfast steps. I uploaded the urdf, dae and I regenerated the database.

**Comment by chinmay1148** [comment]
Thank you for uploading urdf and dae. I am using your repo with pybullet simulator. The output of IKsolver is not as expected.  So was trying to generate new ikfast61.cpp.

I also realize that my ur5 urdf didnot have (baselink --> base) joint. What did you use for parameters "--baselink=1 --eelink=6" while generating IK solver  ?

**Comment by cambel** [comment]
I set them as"--baselink=1 --eelink=10"

**Comment by Mickeyyyang** [comment]
If I have a real UR3e, can I directly use the ikfast plugin your gave in this?

**Comment by cambel** [comment]
@Mickeyyyang Sure you can just be aware that the real UR robots are not identical to the URDF design. They have some calibration parameters to adjust for those small differences. In other words, the IK solution from IKFAST (tip of the end-effector) may be slightly off with respect to the real robot. In my experience with the UR3e, I had no issue with that, I didn't really check, it was good enough for me. For bigger robots, some people reported several millimeters of error. For more info see this thread https://github.com/ros-industrial/universal_robot/issues/564

**Comment by QNXLQ** [comment]
Hello, I'm using yours ur10.cpp and ikfast.h, is normal that sometimes only have 4 or less solution?

**Comment by cambel** [comment]
Yes, It is normal. If I am not wrong a 6 DOF robot has a maximum of 16 valid IK solutions when all joint has a limited range of motion. Then the IKFAST it's just a database of the best poses found, discarding singularities and self-collisions (not sure about that last one but I suppose that is the case). So getting less than 4 or None can happen.
