### ISSUE TITLE
[Question] Does the reference frame match the UR base frame?

### ISSUE THREAD

**Issue by tlpss** [cambel/ur_ikfast#5]
Hi @cambel,

I noticed today that the FK of the zero-joint configuration does not seem to match the frame of the base on the ur controller.

On the ur controller, the pose of the zero-configuration for the joints has a negative X and Y value when expressed in the base frame  (Y along the power cable, z up).

However, the following script
```
    zero_joint_pose = URKinematics("ur3").forward(np.zeros(6))
    print(zero_joint_pose)
```
returns `[ 0.4569      0.19425     0.06655     0.70710678  0.70710678 -0.
 -0.        ]`

Am I doing something wrong or is a transform required to use the IK on a real robot?

**Comment by cambel** [comment]
@tlpss Hi,
Yes, the reference frame `base_link` should match the real robot. The IKFast database was created using the official URDF of the robot. I also have been using it without a problem.

**Comment by tlpss** [comment]
@cambel, thanks for your reply. I figured you had used it on real robots, which is why I was surprised..

I haven't had time to look further into this but will try to test it on a real UR3e soon. Probably I've made a mistake somewhere.

**Comment by tlpss** [comment]
@cambel, quickly wanted to add something:

The [docs of the ROS2 driver](https://docs.ros.org/en/ros2_packages/rolling/api/ur_robot_driver/usage.html#robot-frames) seem to confirm that the `base_link` frame does not match the robot's control box frame (which corresponds to the `base` frame):

> While most tf frames come from the URDF and are published from the robot_state_publisher, there are a couple of things to know: 
> - The base frame is the robot’s base as the robot controller sees it.
> - ...

I.e.  if you read the current pose from the control box, do IK using this package and then send the robot to that joint configuration, it will end up in a different pose on the control box, as this package uses the `base_link` as reference frame.  If you do everything within the ROS framework and ignore the control box, you won't encounter this as the `base_link` is mostly used as the reference frame, such as [here](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/blob/f6ae95864ea2def291e73afb6dce6ab810260316/ur_moveit_config/config/ur_servo.yaml#L40) for Moveit servo.
