### ISSUE TITLE
cc1plus: fatal error: ur3e_ikfast_wrapper.cpp: No such file or directory

### ISSUE THREAD

**Issue by ocg2347** [cambel/ur_ikfast#7]
Hi, thank you for this practical and so-far-nice-working repo :)
Today I was trying to build this module on my brand new ubuntu (22.04) OS and got the error below. I thought it might be related to gcc version because it is 9.4.0 on other pc that I built the module flawlessly and now I am trying to build it on new pc which has 11.4.0. After installing gxx=9.4.0 on a mamba environment nothing changed.
What should I check, what do you say?

>     ur3e/ur3e_ikfast61.cpp:107156:8: warning: unused variable ‘gconst69’ [-Wunused-variable]
>     107156 | IkReal gconst69=((3.14159265358979)+(((-1.0)*x15683)));
>            |        ^~~~~~~~
>     ur3e/ur3e_ikfast61.cpp:107123:8: warning: unused variable ‘gconst69’ [-Wunused-variable]
>     107123 | IkReal gconst69=((3.14159265358979)+(((-1.0)*x15679)));
>            |        ^~~~~~~~
>     ur3e/ur3e_ikfast61.cpp:107086:8: warning: unused variable ‘gconst69’ [-Wunused-variable]
>     107086 | IkReal gconst69=((3.14159265358979)+(((-1.0)*(x15675.value))));
>            |        ^~~~~~~~
>     ur3e/ikfast_wrapper.cpp: In member function ‘std::vector<float> robots::Kinematics::forward(std::vector<float>)’:
>     ur3e/ikfast_wrapper.cpp:114:33: warning: comparison of integer expressions of different signedness: ‘std::vector<float>::size_type’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
>       114 |         if( joint_config.size() != num_of_joints ) {
>           |             ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
>     ur3e/ikfast_wrapper.cpp:121:33: warning: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘int’ [-Wsign-compare]
>       121 |         for (unsigned int i=0; i<num_of_joints; i++)
>           |                                ~^~~~~~~~~~~~~~
>     cc1plus: fatal error: ur3e_ikfast_wrapper.cpp: No such file or directory
>     compilation terminated.
>     error: command '/usr/bin/gcc' failed with exit code 1
>     [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with

**Comment by fredsukkar** [comment]
did you end up solving this? Having the same issue, using ubuntu 20.04.2, gcc version 9.4.0.

Edit: fixed by installing an older version of Cython (0.29.21 for reference)

**Comment by cambel** [comment]
Hi @ocg2347 

I finally checked this issue. There was a problem with the configuration of Cython that was not a problem in older versions of Cython as discover by @fredsukkar 

If you pull the latest commit, it should compile with the latest Cython and probably it will be fine in Ubuntu 22.04 too, though I have not tested that yet.

**Comment by ocg2347** [comment]
> did you end up solving this? Having the same issue, using ubuntu 20.04.2, gcc version 9.4.0.
> 
> Edit: fixed by installing an older version of Cython (0.29.21 for reference)

Thank you!



> Hi @ocg2347
> 
> I finally checked this issue. There was a problem with the configuration of Cython that was not a problem in older versions of Cython as discover by @fredsukkar
> 
> If you pull the latest commit, it should compile with the latest Cython and probably it will be fine in Ubuntu 22.04 too, though I have not tested that yet.

And thank you. :)

**Comment by cambel** [comment]
I have confirmed that it builds correctly in Ubuntu 22.04
